project:
  type: website
  output-dir: docs

website:
  title: "RSE: How to"
  back-to-top-navigation: true
  page-navigation: true
  site-url: https://murphyqm.github.io/research-software-dev/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://github.com/murphyqm/python-project-template
        text: Launch virtual machine
        target: _blank
  sidebar:
    border: false
    style: "docked"
    search: false
    contents:
      - section: "Introduction"
        contents:
        - text: "Course page"
          href: index.qmd
        - text: "Introduction Slides"
          href: intro-presentation/intro.qmd
      - section: "Basic Linux"
        contents:
        - href: intro-to-linux-files/intro-to-linux-page.qmd
          text: Intro to Linux
        - href: intro-to-linux-files/linux101.qmd
          text: Linux 101 slides
      - section: "Managing dependencies"
        contents:
          - href: managing-dependencies/dependencies-intro.qmd
            text: Basic dependencies in Python
          - href: managing-dependencies/dep-pres.qmd
            text: Dependency slides
          - href: managing-dependencies/conda-skills.qmd
            text: Conda skills
          - href: managing-dependencies/dependencies-old-projects.qmd
            text: Figuring out dependencies for old code
      - section: "Version control with git"
        contents:
          - href: version_control/version_control.qmd
            text: Introduction to Version Control
          - href: version_control/version_control_slides.qmd
            text: Version control intro slides

format:
  html:
    page-layout: full
    mainfont: Space Grotesk
    theme:
      - custom.scss
    toc: true
    footnotes-hover: true

comments:
  utterances:
    repo: murphyqm/research-software-dev

bibliography: refs.bib