project:
  type: website
  output-dir: docs

website:
  title: "RSE: How to"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
      - custom.scss
    toc: true



