project:
  type: website
  output-dir: docs

website:
  title: "RSE: How to"
  back-to-top-navigation: true
  page-navigation: true
  site-url: https://murphyqm.github.io/research-software-dev/
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    border: false
    style: "docked"
    search: false
    contents:
      - section: "Introduction"
        contents:
        - text: "Course page"
          href: index.qmd
        - text: "Introduction Slides"
          href: intro-presentation/intro.qmd
      - section: "Basic Linux"
        contents:
        - href: intro-to-linux-files/intro-to-linux-page.qmd
          text: Intro to Linux
        - href: intro-to-linux-files/linux101.qmd
          text: Linux 101 slides
      - section: "Managing dependencies"

format:
  html:
    page-layout: full
    mainfont: Space Grotesk
    theme:
      - custom.scss
    toc: true
    footnotes-hover: true

comments:
  utterances:
    repo: murphyqm/research-software-dev

bibliography: refs.bib