project:
  type: website
  output-dir: docs

website:
  title: "RSE: How to"
  back-to-top-navigation: true
  page-navigation: true
  site-url: https://murphyqm.github.io/research-software-dev/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro-to-linux-files/intro-to-linux-page.qmd
        text: Intro to Linux
  sidebar:
    border: false
    style: "docked"
    search: false
    contents:
      - text: "Introduction"
        href: index.qmd

format:
  html:
    page-layout: full
    mainfont: Space Grotesk
    theme:
      - custom.scss
    toc: true
    footnotes-hover: true

comments:
  utterances:
    repo: murphyqm/research-software-dev

bibliography: refs.bib